version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
    - "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -"
    - "curl -sL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -"
    - "apt update"
    - "apt install -y wget dpkg rpm"
    - "pip3 install boto3"
    - "wget https://github.com/aquasecurity/trivy/releases/download/v0.58.0/trivy_0.58.0_Linux-64bit.deb"
    - "dpkg -i trivy_0.58.0_Linux-64bit.deb"
  pre_build:
    commands:
    - "$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)"
    - "docker build -t $docker_img_name:$docker_tag ."
  build:
    commands:
    - trivy image $docker_img_name:$docker_tag
    - trivy --exit-code 1 -f json -o result.json image $docker_img_name:$docker_tag
    - docker tag $docker_img_name:$docker_tag $ecr_repo:latest
    - docker push $ecr_repo:latest
  post_build:
    commands:
    - echo trivy scan completed on `date`
    - python3 sechub_parser.py
    - echo Report Sent to Security Hub on `date`
